name: location_tracker
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^6.0.0
  bloc: ^6.0.3
  equatable: ^1.2.5
  firestore_api:
    git:
      url: https://github.com/dartclub/firestore_dart
      path: firestore_api
  turf: ^0.0.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  